"""add processing job progress fields

Revision ID: c8a6a01bde31
Revises: e6d4b0d91577
Create Date: 2026-08-06 21:08:23.530028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8a6a01bde31'
down_revision: Union[str, Sequence[str], None] = 'e6d4b0d91577'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processing_jobs', sa.Column('progress_percent', sa.Integer(), server_default='0', nullable=False))
    op.add_column('processing_jobs', sa.Column('progress_stage', sa.String(length=100), nullable=True))
    op.add_column('processing_jobs', sa.Column('progress_message', sa.String(length=255), nullable=True))
    op.add_column('processing_jobs', sa.Column('progress_current', sa.Integer(), nullable=True))
    op.add_column('processing_jobs', sa.Column('progress_total', sa.Integer(), nullable=True))
    op.add_column('processing_jobs', sa.Column('progress_updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('processing_jobs', 'progress_updated_at')
    op.drop_column('processing_jobs', 'progress_total')
    op.drop_column('processing_jobs', 'progress_current')
    op.drop_column('processing_jobs', 'progress_message')
    op.drop_column('processing_jobs', 'progress_stage')
    op.drop_column('processing_jobs', 'progress_percent')
    # ### end Alembic commands ###
