"""extend webhook delivery logs schema

Revision ID: e6d4b0d91577
Revises: ab25ca1d7f50
Create Date: 2026-08-05 21:36:58.514667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e6d4b0d91577'
down_revision: Union[str, Sequence[str], None] = 'ab25ca1d7f50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processing_jobs', sa.Column('filename', sa.String(length=255), nullable=False))
    op.add_column('webhook_delivery_logs', sa.Column('event_id', sa.String(length=100), nullable=False))
    op.add_column('webhook_delivery_logs', sa.Column('attempt_count', sa.Integer(), nullable=False))
    op.add_column('webhook_delivery_logs', sa.Column('request_url', sa.String(length=500), nullable=False))
    op.add_column('webhook_delivery_logs', sa.Column('response_status', sa.Integer(), nullable=True))
    op.add_column('webhook_delivery_logs', sa.Column('failure_reason', sa.Text(), nullable=True))
    op.add_column('webhook_delivery_logs', sa.Column('dispatch_timestamp', sa.Integer(), nullable=False))
    op.add_column('webhook_delivery_logs', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('webhook_delivery_logs', sa.Column('processing_started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('webhook_delivery_logs', sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('webhook_delivery_logs', 'payload_json',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.Text(),
               existing_nullable=False)
    op.create_index(op.f('ix_webhook_delivery_logs_event_id'), 'webhook_delivery_logs', ['event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webhook_delivery_logs_event_id'), table_name='webhook_delivery_logs')
    op.alter_column('webhook_delivery_logs', 'payload_json',
               existing_type=sa.Text(),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.drop_column('webhook_delivery_logs', 'delivered_at')
    op.drop_column('webhook_delivery_logs', 'processing_started_at')
    op.drop_column('webhook_delivery_logs', 'updated_at')
    op.drop_column('webhook_delivery_logs', 'dispatch_timestamp')
    op.drop_column('webhook_delivery_logs', 'failure_reason')
    op.drop_column('webhook_delivery_logs', 'response_status')
    op.drop_column('webhook_delivery_logs', 'request_url')
    op.drop_column('webhook_delivery_logs', 'attempt_count')
    op.drop_column('webhook_delivery_logs', 'event_id')
    op.drop_column('processing_jobs', 'filename')
    # ### end Alembic commands ###
